name: hello-world
on: push

jobs:
  simple-hello-world:

   runs-on: ubuntu-latest

   steps:
     - name: Checkout Repo
       uses: actions/checkout@v6

     - run: echo "$(cat hello_world.txt)"
  
